# Default values for enabler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# String to partially override enabler.fullname template (will maintain the release name)
nameOverride: ""
# String to fully override enabler.fullname template
fullnameOverride: ""
# Deploy all the components in specific K8s node(s)
enablerNodeSelector: {}
# Cilium Multi-cluster global service
globalService: false

# Component api values
api:
  tier: external
  replicaCount: 1

  # Configuration of the container image
  imagePullSecrets: []
  image:
    repository: assistiot/vpn
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    pullPolicy: IfNotPresent
  
  # Configuration of the service: type and ports
  service:
    type: NodePort
    ports:
      api:
        port: 3000
        targetPort: 3000
        containerPort: 3000
        nodePort: ""
        protocol: TCP
      wireguard:
        port: 51820
        targetPort: 51820
        containerPort: 51820
        nodePort: ""
        protocol: UDP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    # minReplicas: 1
    # maxReplicas: 3
    # targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  envVars:
    wgPrivateKey: "qAuVUEbmcI3ofLsjJmQ6+RtEejoNX+WHs7QOsIccn0Y="
    serverIP: "192.168.1.1"
    wgSubnet: "192.168.2.1/24"
    peerAllowedIPs: "0.0.0.0/0,::/0"
    ltse: true
    ltseUrl: "http://ltse-api:8080"
    ltseIndex: vpn-enabler
  
  # Configure the usage of an external database (not deployed using this chart)
  externalDatabase:
    enabled: false
    host: vpn-db
    port: 27017
    username: vpnenabler
    password: 4ss1st10t

  # Configure this parameters to deploy the component in specific K8s node(s)
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Component db values
db:
  tier: internal
  replicaCount: 1

  # Configuration of the container image
  imagePullSecrets: []
  image:
    repository: mongo
    # Overrides the image tag whose default is the chart appVersion.
    tag: "4.4.13"
    pullPolicy: IfNotPresent
  
  # Configuration of the service: type and ports
  service:
    type: ClusterIP
    ports:
      mongo:
        port: 27017
        targetPort: 27017
        containerPort: 27017
        protocol: TCP

  # The specification of the resources is needed for the proper functioning 
  # of the Smart Orchestrator enabler (requests)
  # and of the Resource provisioning enabler (limits)
  resources:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 200m
      memory: 256Mi

  autoscaling:
    enabled: false

  podSecurityContext: {}
  securityContext: {}

  # Include here the environment variables to be used in the component's manifest (container section).
  envVars:
    username: vpnenabler
    password: 4ss1st10t

  # Component data persistence
  persistence:
    enabled: true
    existingClaim: ""
    # mountPath: /path/in/container
    accessModes:
      - ReadWriteOnce
    size: 50Mi

  # Configure this parameters to deploy the component in specific K8s node(s)
  nodeSelector: {}
  tolerations: []
  affinity: {}

