{{- if eq (include "db.deploy" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - name: mongo
      port: {{ .Values.db.service.ports.mongo.port }}
      targetPort: {{ .Values.db.service.ports.mongo.targetPort }}
      protocol: {{ .Values.db.service.ports.mongo.protocol }}
      {{- if and (or (eq .Values.db.service.type "NodePort") (eq .Values.db.service.type "LoadBalancer")) (not (empty .Values.db.service.ports.mongo.nodePort)) }}
      nodePort: {{ .Values.db.service.ports.mongo.nodePort }}
      {{- end }}
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
{{- end }}