{{- if .Values.globalService }}
apiVersion: assist.eu/v1
kind: MultiClusterService
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    io.cilium/global-service: "true"
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      port: {{ .Values.api.service.ports.api.port }}
      targetPort: {{ .Values.api.service.ports.api.targetPort }}
      protocol: {{ .Values.api.service.ports.api.protocol }}
    - name: wireguard
      port: {{ .Values.api.service.ports.wireguard.port }}
      targetPort: {{ .Values.api.service.ports.wireguard.targetPort }}
      protocol: {{ .Values.api.service.ports.wireguard.protocol }}
{{- end }}